'use strict';
const C=document.getElementById('world'), ctx=C.getContext('2d',{alpha:false});
const DPR=()=>Math.min(devicePixelRatio||1,2);
let W=0,H=0,dpr=1;
function resize(){dpr=DPR();W=innerWidth;H=innerHeight;C.width=Math.round(W*dpr);C.height=Math.round(H*dpr);C.style.width=W+'px';C.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize,{passive:true}); resize();

const palette={ink:'#08060d',paper:'#f4f0e7',acid:'#b5ff48',cyan:'#36e7ff',pink:'#ff4ec7',violet:'#6b3cff',red:'#ff5a61',gold:'#ffd454'};
const zones=[
 {id:'image',n:'IMAGE SYSTEMS',sub:'AURELIA / KNOT',x:-460,y:-300,c:palette.pink,c2:palette.cyan,title:'MAKE THE IMAGE FEEL LIKE A WORLD.',body:'AURELIA and KNOT are visual-system studies built around continuity, material language and repeatable art direction. The point is not one good render. The point is a visual language that survives the next twenty.',tags:['VISUAL SYSTEMS','CHARACTERS','PRODUCT WORLDS','ART DIRECTION']},
 {id:'video',n:'MOTION LAB',sub:'THE ALGORITHM / SPEC ADS',x:450,y:-320,c:palette.red,c2:palette.pink,title:'MOTION WITH A MEMORY.',body:'Short-form ads and cinematic sequences designed around repeatable shot logic, continuity rules and deliberate camera language instead of hoping every generation remembers what the last one looked like.',tags:['VIDEO','SCENE BOARDS','CONTINUITY','CAMPAIGNS']},
 {id:'brand',n:'BRAND MUTATION',sub:'FORM/01 / GRIDLINE',x:-450,y:340,c:palette.acid,c2:palette.gold,title:'A BRAND SHOULD HAVE A PHYSICS ENGINE.',body:'Identity, packaging, mascot logic, product language and web art direction designed to feel like the same universe. Fewer disconnected assets. More recognizable behavior.',tags:['BRAND SYSTEMS','PACKAGING','IDENTITY','ART DIRECTION']},
 {id:'code',n:'INTERACTIVE BUILDS',sub:'GIVEMEPROMPTS / DIMENSION 404',x:470,y:330,c:palette.cyan,c2:palette.violet,title:'THE PITCH SHOULD BE SOMETHING YOU CAN TOUCH.',body:'Interactive prototypes and sites that prove the idea by existing. Motion, tools and playable systems are part of the communication, not decorative garnish around a sales paragraph.',tags:['WEB','INTERACTION','PROTOTYPES','PRODUCT']},
 {id:'agent',n:'AGENT FACTORY',sub:'FRONT OFFICE / GAUNTLET',x:0,y:600,c:palette.gold,c2:palette.acid,title:'TURN THE GOOD IDEA INTO A REPEATABLE WORKER.',body:'Research, follow-up, production and QA workflows that move repetitive work out of people’s heads and into systems that can be tested, improved and reused.',tags:['AGENTS','AUTOMATION','WORKFLOWS','QA']}
];
function loadSeen(){try{return JSON.parse(localStorage.getItem('d404-v10-seen')||'[]')}catch(e){return []}}
const state={started:false,seen:new Set(loadSeen()),x:0,y:40,angle:-Math.PI/2,speed:0,target:null,drag:false,dragStart:null,dragPt:null,zoom:(innerWidth<700?1.02:1.28),camX:0,camY:40,time:0,selected:null,jump:0,jumpV:0,downAt:0,downPos:null,carScreen:[0,0]};
const ui={intro:document.getElementById('intro'),project:document.getElementById('project'),map:document.getElementById('map'),progress:document.querySelector('#progress strong'),zoneTag:document.getElementById('zoneTag'),hint:document.getElementById('hint'),indicator:document.getElementById('driveIndicator'),line:document.getElementById('driveLine'),toast:document.getElementById('toast')};
function persist(){try{localStorage.setItem('d404-v10-seen',JSON.stringify([...state.seen]))}catch(e){}}
function toast(msg){ui.toast.querySelector('div').textContent=msg;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),2600)}
function updateProgress(){ui.progress.textContent=state.seen.size+'/5';renderMap()}
function worldToScreen(x,y){const rx=x-state.camX, ry=y-state.camY;return [W/2+(rx-ry)*.58*state.zoom,H*.60+(rx+ry)*.30*state.zoom]}
function screenToWorld(sx,sy){const a=(sx-W/2)/(.58*state.zoom)+(state.camX-state.camY);const b=(sy-H*.60)/(.30*state.zoom)+(state.camX+state.camY);return [(a+b)/2,(b-a)/2]}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function line(x1,y1,x2,y2,w,c,a=1){ctx.globalAlpha=a;ctx.strokeStyle=c;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.globalAlpha=1}
function poly(points,fill,stroke=null,lw=1){ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length;i++)ctx.lineTo(points[i][0],points[i][1]);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function text(t,x,y,size,c=palette.paper,align='left',weight=900){ctx.fillStyle=c;ctx.font=`${weight} ${size}px Inter, system-ui, sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(t,x,y)}
function shadowText(t,x,y,size,c,align='left'){text(t,x+4,y+5,size,'rgba(0,0,0,.52)',align,1000);text(t,x,y,size,c,align,1000)}
function worldPoly(points,fill,stroke=null,lw=1){poly(points.map(p=>worldToScreen(p[0],p[1])),fill,stroke,lw)}
function drawGround(){
 ctx.fillStyle='#08050c';ctx.fillRect(0,0,W,H);
 const g=ctx.createRadialGradient(W*.52,H*.48,20,W*.52,H*.48,Math.max(W,H)*.8);g.addColorStop(0,'#221036');g.addColorStop(.42,'#100918');g.addColorStop(1,'#06040a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
 ctx.save();ctx.globalAlpha=.18;const span=1500,step=100;
 for(let x=-span;x<=span;x+=step){const a=worldToScreen(x,-span),b=worldToScreen(x,span);line(a[0],a[1],b[0],b[1],1,'#78638f',.13)}
 for(let y=-span;y<=span;y+=step){const a=worldToScreen(-span,y),b=worldToScreen(span,y);line(a[0],a[1],b[0],b[1],1,'#78638f',.13)}
 ctx.restore();
 worldPoly([[-900,-58],[900,-58],[900,58],[-900,58]],'#15101e','#24182f',1);worldPoly([[-58,-900],[58,-900],[58,900],[-58,900]],'#15101e','#24182f',1);
 const ca=worldToScreen(-900,0),cb=worldToScreen(900,0),cc=worldToScreen(0,-900),cd=worldToScreen(0,900);line(ca[0],ca[1],cb[0],cb[1],2,palette.acid,.18);line(cc[0],cc[1],cd[0],cd[1],2,palette.cyan,.16);
 worldPoly([[-135,-135],[135,-135],[135,135],[-135,135]],'#1b1027','#443052',2);worldPoly([[-120,-120],[120,-120],[120,120],[-120,120]],'#0c0912','#6b3cff',1.5);
 zones.forEach(z=>{const a=worldToScreen(0,0),b=worldToScreen(z.x,z.y);line(a[0],a[1],b[0],b[1],11*state.zoom,'#08060d',.72);line(a[0],a[1],b[0],b[1],2.2*state.zoom,z.c,.38)});
}
function drawStickerProp(x,y,type,c,rot=0,sc=1){
 const p=worldToScreen(x,y),S=state.zoom*sc;ctx.save();ctx.translate(p[0],p[1]);ctx.rotate(rot);ctx.save();ctx.translate(6*S,7*S);ctx.globalAlpha=.55;ctx.fillStyle='#020104';
 if(type==='eye'){ctx.fillRect(-4*S,-40*S,8*S,44*S);ctx.beginPath();ctx.ellipse(0,-47*S,23*S,15*S,0,0,Math.PI*2);ctx.fill()}else if(type==='tape')ctx.fillRect(-13*S,-48*S,26*S,56*S);else if(type==='shard')poly([[-22*S,-34*S],[18*S,-44*S],[28*S,-3*S],[-13*S,9*S]],'#020104');else {ctx.beginPath();ctx.arc(0,-28*S,22*S,0,Math.PI*2);ctx.fill()}ctx.restore();
 if(type==='eye'){ctx.fillStyle='#0b0811';ctx.fillRect(-3*S,-40*S,6*S,42*S);ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(0,-48*S,22*S,14*S,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#08060d';ctx.lineWidth=3*S;ctx.stroke();ctx.fillStyle='#08060d';ctx.beginPath();ctx.arc(3*S,-48*S,6*S,0,Math.PI*2);ctx.fill()}else if(type==='tape'){ctx.fillStyle=c;ctx.fillRect(-12*S,-48*S,24*S,55*S);ctx.fillStyle='#08060d';ctx.fillRect(-12*S,-18*S,24*S,6*S);ctx.fillStyle='#08060d';ctx.font=`1000 ${6*S}px Inter`;ctx.textAlign='center';ctx.fillText('404',0,-32*S)}else if(type==='shard'){poly([[-22*S,-34*S],[18*S,-44*S],[28*S,-3*S],[-13*S,9*S]],c,'#08060d',2*S);line(-11*S,-22*S,17*S,-29*S,3*S,'#08060d',1);line(-7*S,-10*S,12*S,-15*S,2*S,'#08060d',1)}else{ctx.strokeStyle=c;ctx.lineWidth=3*S;ctx.beginPath();ctx.arc(0,-28*S,21*S,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(0,-28*S,9*S,0,Math.PI*2);ctx.stroke();line(-30*S,-28*S,30*S,-28*S,2*S,c,.8)}ctx.restore();
}
function drawDeco(){
 const props=[[-300,-60,'eye',palette.pink,-.08,.9],[310,-95,'tape',palette.cyan,.08,.9],[-330,220,'shard',palette.acid,-.12,1],[350,215,'node',palette.violet,.08,.95],[-160,390,'eye',palette.gold,.08,.8],[170,420,'shard',palette.cyan,-.1,.85],[610,-30,'tape',palette.red,.08,.8],[-610,30,'node',palette.acid,-.08,.8],[-90,-470,'eye',palette.cyan,.05,.8],[100,-540,'shard',palette.pink,-.06,.8]];props.forEach(q=>drawStickerProp(...q));
 const c=worldToScreen(0,0);ctx.save();ctx.translate(c[0],c[1]-14*state.zoom);for(let k=0;k<3;k++){ctx.strokeStyle=[palette.violet,palette.cyan,palette.acid][k];ctx.globalAlpha=.45-k*.08;ctx.lineWidth=(8-k*2)*state.zoom;ctx.beginPath();ctx.ellipse(0,0,(82-k*18)*state.zoom,(32-k*7)*state.zoom,-.08,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;shadowText('404',0,-8*state.zoom,46*state.zoom,palette.paper,'center');text('CENTRAL LAB',0,27*state.zoom,7.5*state.zoom,palette.acid,'center',1000);ctx.restore();
 const dec=[[-245,-115,'// RAW IDEA',palette.acid,-.08],[245,120,'SHIP >',palette.cyan,.05],[-110,470,'SYSTEMS / NOT TRICKS',palette.paper,-.04]];for(const [x,y,t,c,rot] of dec){const p=worldToScreen(x,y);ctx.save();ctx.translate(p[0],p[1]);ctx.rotate(rot);ctx.globalAlpha=.38;text(t,0,0,10*state.zoom,c,'center',1000);ctx.restore()}
}
function drawIsoBox(x,y,w,d,h,c,edge='#08060d'){const A=worldToScreen(x-w/2,y-d/2),B=worldToScreen(x+w/2,y-d/2),C=worldToScreen(x+w/2,y+d/2),D=worldToScreen(x-w/2,y+d/2);const lift=h*state.zoom;poly([A,B,C,D],c,edge,1.5);poly([[D[0],D[1]],[C[0],C[1]],[C[0],C[1]-lift],[D[0],D[1]-lift]],'#09060d',edge,1);poly([[B[0],B[1]],[C[0],C[1]],[C[0],C[1]-lift],[B[0],B[1]-lift]],'#120a19',edge,1);return {A,B,C,D,lift}}
function drawZoneSet(z,idx){const t=state.time;const plat=[[-155,-105],[155,-105],[155,105],[-155,105]].map(p=>[z.x+p[0],z.y+p[1]]);worldPoly(plat,'#100a18',z.c,2);const lip=plat.map(p=>worldToScreen(p[0],p[1]));poly([[lip[3][0],lip[3][1]],[lip[2][0],lip[2][1]],[lip[2][0],lip[2][1]+10*state.zoom],[lip[3][0],lip[3][1]+10*state.zoom]],'#050308');if(z.id==='image'){for(let k=0;k<3;k++){const x=z.x-150+k*70,y=z.y+90+(k%2)*28,p=worldToScreen(x,y);drawIsoBox(x,y,44,44,27,z.c2);ctx.strokeStyle=z.c;ctx.lineWidth=4*state.zoom;ctx.beginPath();ctx.arc(p[0],p[1]-25*state.zoom,14*state.zoom,0,Math.PI*2);ctx.stroke()}}else if(z.id==='video'){for(let k=0;k<3;k++){const x=z.x-120+k*80,y=z.y+100;drawIsoBox(x,y,62,38,32,k===1?z.c:z.c2);const p=worldToScreen(x,y);line(p[0]-15*state.zoom,p[1]-35*state.zoom,p[0]+15*state.zoom,p[1]-35*state.zoom,4*state.zoom,'#08060d',1)}}else if(z.id==='brand'){drawIsoBox(z.x-125,z.y+105,74,64,74,z.c);drawIsoBox(z.x-35,z.y+118,52,52,48,z.c2);drawIsoBox(z.x+45,z.y+105,82,60,32,palette.paper)}else if(z.id==='code'){for(let k=0;k<4;k++){const x=z.x-130+k*70,y=z.y+105+(k%2)*18;drawIsoBox(x,y,30,30,64+k*11,k%2?z.c2:z.c)}}else{for(let k=0;k<5;k++){const a=k/5*Math.PI*2+t*.18,x=z.x+Math.cos(a)*105,y=z.y+110+Math.sin(a)*52,p=worldToScreen(x,y);ctx.fillStyle=k%2?z.c:z.c2;ctx.beginPath();ctx.arc(p[0],p[1]-18*state.zoom,9*state.zoom,0,Math.PI*2);ctx.fill();line(p[0],p[1]-9*state.zoom,p[0],p[1]+6*state.zoom,2*state.zoom,'#4d3e58',.7)}}}
